---
- name: add Node.js apt
  sudo: yes
  shell: "curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -"

- name: Install Node.js
  sudo: yes
  apt: pkg=nodejs

- name: make sure the latest npm is installed
  sudo: yes
  command: npm install -g npm

- name: Install forever
  sudo: yes
  npm: name=forever global=yes state=latest
